[pytest]
pythonpath = .
testpaths = tests
addopts = -q
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::FutureWarning
    ignore::UserWarning
    ignore::RuntimeWarning:.*scispacy.*
    ignore::RuntimeWarning:.*sentence_transformers.*
    ignore::RuntimeWarning:.*torch.*
    ignore::DeprecationWarning:.*pkg_resources.*
    ignore::DeprecationWarning:.*numpy.*
    ignore::DeprecationWarning:.*scipy.*